// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6zDJUVaR2hnbNBsosFuf7f5PxMnpLf4',
    appId: '1:356560069025:android:d1383d8e544de0335d2be0',
    messagingSenderId: '356560069025',
    projectId: 'temi-wa',
    storageBucket: 'temi-wa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRxjivKzbpdHj9qN55WiUH-putyE6wc4o',
    appId: '1:356560069025:ios:463ea4da5502544b5d2be0',
    messagingSenderId: '356560069025',
    projectId: 'temi-wa',
    storageBucket: 'temi-wa.firebasestorage.app',
    androidClientId: '356560069025-22oh6n0shs56ie3qh0dvqrieau4un892.apps.googleusercontent.com',
    iosClientId: '356560069025-77sml87021hjg4j34vqsm77h814lncb3.apps.googleusercontent.com',
    iosBundleId: 'com.temiwa',
  );

}